/**
 * The gated delta linear attention family, in JavaScript.
 *
 * The interactive figures in the writeup compute the real recurrence in the browser
 * rather than replaying a recording. That is only worth doing if the browser copy is
 * actually the same maths as the tested Python one, so `kda-math.test.js` checks this
 * file against fixtures generated by `scripts/export_widget_data.py` from
 * `kda.recurrent.linear_attn`.
 *
 * The usual failure of an illustrated explainer is an animation that quietly disagrees
 * with the equations beside it. This is the cheapest available defence.
 *
 * Everything is plain nested arrays -- dimensions here are tiny (d = 4..8, T = 8..32),
 * so clarity beats performance.
 */

/** S_t = (I - b_t k_t k_t^T) Diag(a_t) S_{t-1} + b_t k_t v_t^T ;  o_t = S_t^T q_t
 *
 * @param {number[][]} q  [T][dk]
 * @param {number[][]} k  [T][dk]
 * @param {number[][]} v  [T][dv]
 * @param {object} opts
 *   alpha  [T][dk] per-channel decay in (0,1]; or [T] scalars; or null for no gate
 *   beta   [T] write strength; defaults to all ones
 *   gate   "none" | "scalar" | "channel"
 *   delta  boolean -- whether the write corrects the existing memory
 * @returns {{outputs:number[][], states:number[][][], errors:number[][]}}
 *   `states[t]` is a [dk][dv] snapshot after step t, so a widget can scrub through
 *   time; `errors[t]` is the delta-rule residual v_t - (G S)^T k_t, which is what the
 *   rule actually writes.
 */
export function linearAttn(q, k, v, opts = {}) {
  const { alpha = null, beta = null, gate = "channel", delta = true } = opts;
  const T = q.length;
  const dk = q[0].length;
  const dv = v[0].length;

  let S = zeros2(dk, dv);
  const outputs = [];
  const states = [];
  const errors = [];

  for (let t = 0; t < T; t++) {
    // 1. decay: G_t S_{t-1}
    if (gate === "scalar") {
      const a = alpha[t];
      for (let i = 0; i < dk; i++) for (let j = 0; j < dv; j++) S[i][j] *= a;
    } else if (gate === "channel") {
      for (let i = 0; i < dk; i++) {
        const a = alpha[t][i];
        for (let j = 0; j < dv; j++) S[i][j] *= a;
      }
    }

    // 2. what to write: the value, or the error between it and what memory answers
    const b = beta ? beta[t] : 1;
    const target = new Array(dv);
    if (delta) {
      const pred = stateTranspose(S, k[t], dk, dv);   // (G S)^T k_t
      for (let j = 0; j < dv; j++) target[j] = v[t][j] - pred[j];
    } else {
      for (let j = 0; j < dv; j++) target[j] = v[t][j];
    }
    errors.push(target.slice());

    // 3. write it
    for (let i = 0; i < dk; i++) {
      const ki = b * k[t][i];
      if (ki === 0) continue;
      for (let j = 0; j < dv; j++) S[i][j] += ki * target[j];
    }

    // 4. read with the updated state
    outputs.push(stateTranspose(S, q[t], dk, dv));
    states.push(S.map((row) => row.slice()));
  }
  return { outputs, states, errors };
}

/** S^T x for S of shape [dk][dv] and x of length dk. */
export function stateTranspose(S, x, dk, dv) {
  const out = new Array(dv).fill(0);
  for (let i = 0; i < dk; i++) {
    const xi = x[i];
    if (xi === 0) continue;
    for (let j = 0; j < dv; j++) out[j] += S[i][j] * xi;
  }
  return out;
}

/** Causal softmax attention, for the side-by-side comparison. */
export function softmaxAttn(q, k, v) {
  const T = q.length;
  const dk = q[0].length;
  const scale = 1 / Math.sqrt(dk);
  const outputs = [];
  const weights = [];
  for (let t = 0; t < T; t++) {
    const s = [];
    for (let j = 0; j <= t; j++) s.push(dot(q[t], k[j]) * scale);
    const m = Math.max(...s);
    const e = s.map((x) => Math.exp(x - m));
    const z = e.reduce((a, b) => a + b, 0);
    const w = e.map((x) => x / z);
    const o = new Array(v[0].length).fill(0);
    for (let j = 0; j <= t; j++) for (let d = 0; d < o.length; d++) o[d] += w[j] * v[j][d];
    outputs.push(o);
    weights.push(w);
  }
  return { outputs, weights };
}

/**
 * What plain linear attention retrieves for a key, split into signal and interference.
 *
 * Writing pairs (k_i, v_i) with S = sum_i k_i v_i^T and querying with k_j gives
 *
 *     S^T k_j = |k_j|^2 v_j  +  sum_{i != j} (k_i . k_j) v_i
 *               '--signal--'    '-------interference-------'
 *
 * The second term is zero only if the keys are orthogonal. In a d-dimensional state
 * you get at most d orthogonal keys, so past that point every write corrupts the
 * others -- which is the problem the delta rule exists to solve.
 */
export function interference(keys, values, queryIndex) {
  const dv = values[0].length;
  const kq = keys[queryIndex];
  const signal = new Array(dv).fill(0);
  const noise = new Array(dv).fill(0);
  const contributions = [];
  for (let i = 0; i < keys.length; i++) {
    const c = dot(keys[i], kq);
    const target = i === queryIndex ? signal : noise;
    for (let d = 0; d < dv; d++) target[d] += c * values[i][d];
    contributions.push({ index: i, overlap: c });
  }
  return { signal, noise, contributions, total: signal.map((s, d) => s + noise[d]) };
}

/** Cumulative decay gamma_t = prod_{j<=t} alpha_j, per channel. Shape [T][dk]. */
export function cumulativeDecay(alpha) {
  const out = [];
  let acc = alpha[0].map(() => 1);
  for (let t = 0; t < alpha.length; t++) {
    acc = acc.map((a, i) => a * alpha[t][i]);
    out.push(acc.slice());
  }
  return out;
}

/**
 * FLOPs per head, from Sec. 6.3.
 *   KDA:  6 T d^2 + 3 T C d + T C^2      linear in T
 *   attn: 2 T^2 d                        quadratic in T
 */
export function flops(T, d, C = 64) {
  return {
    kda: 6 * T * d * d + 3 * T * C * d + T * C * C,
    attention: 2 * T * T * d,
  };
}

/**
 * Bytes that must be kept to generate the next token.
 * Attention keeps K and V for every position; KDA keeps one Dk x Dv state per head.
 */
export function cacheBytes({ seqLen, layers, heads, headDim, bytesPerElem = 2, kdaPerAttn = null }) {
  const dModel = heads * headDim;
  const plan = layerPlan(layers, kdaPerAttn);
  const nAttn = plan.filter((x) => x === "full").length;
  const nKda = plan.filter((x) => x === "linear").length;
  return {
    attention: nAttn * 2 * seqLen * dModel * bytesPerElem,
    kda: nKda * heads * headDim * headDim * bytesPerElem,
    nAttn,
    nKda,
  };
}

/** Which layers are linear and which are full attention (mirrors kda.model.layer_plan). */
export function layerPlan(nLayers, kdaPerAttn) {
  if (kdaPerAttn === null || kdaPerAttn === undefined) return Array(nLayers).fill("linear");
  if (kdaPerAttn === 0) return Array(nLayers).fill("full");
  return Array.from({ length: nLayers }, (_, i) =>
    (i + 1) % (kdaPerAttn + 1) === 0 ? "full" : "linear"
  );
}

/** Deterministic PRNG so a widget renders the same thing on every reload. */
export function mulberry32(seed) {
  let a = seed >>> 0;
  return function () {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

export function randomUnit(rng, d) {
  const x = Array.from({ length: d }, () => rng() * 2 - 1);
  return normalize(x);
}

export function normalize(x) {
  const n = Math.hypot(...x) || 1;
  return x.map((a) => a / n);
}

export function dot(a, b) {
  let s = 0;
  for (let i = 0; i < a.length; i++) s += a[i] * b[i];
  return s;
}

function zeros2(a, b) {
  return Array.from({ length: a }, () => new Array(b).fill(0));
}
